// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  deviceId: __t.string().primaryKey().name("device_id"),
  displayName: __t.string().name("display_name"),
  colorU32: __t.u32().name("color_u_32"),
  entityId: __t.u64().name("entity_id"),
  ownerIdentity: __t.identity().name("owner_identity"),
  characterClass: __t.string().name("character_class"),
  hp: __t.u32(),
  maxHp: __t.u32().name("max_hp"),
  spawnX: __t.f32().name("spawn_x"),
  spawnY: __t.f32().name("spawn_y"),
  spawnZ: __t.f32().name("spawn_z"),
});
