// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import RegisterPlayerReducer from "../register_player_reducer";
import SetEntityTransformReducer from "../set_entity_transform_reducer";

export type RegisterPlayerParams = __Infer<typeof RegisterPlayerReducer>;
export type SetEntityTransformParams = __Infer<typeof SetEntityTransformReducer>;

