// Generated by repo-actions/build-sprite-atlas.mjs from zylem-man-sprites.png.
// Do not edit by hand; run `pnpm build:sprite-atlas` instead.

import atlasUrl from './zylem-man-atlas.png';

/** Uniform-grid sheet descriptor, consumed by `createSprite({ sheet })`. */
export const ZYLEM_MAN_SHEET = {
	file: atlasUrl,
	columns: 6,
	rows: 5,
	filter: 'nearest' as const,
	frames: [
		'idle-0', 'idle-1', 'idle-2', 'idle-3', null, null,
		'walk-0', 'walk-1', 'walk-2', 'walk-3', 'walk-4', 'walk-5',
		'run-0', 'run-1', 'run-2', 'run-3', 'run-4', null,
		'duck-0', 'duck-1', null, null, null, null,
		'jump-0', 'jump-1', 'jump-2', 'jump-3', null, null,
	],
};

/** Flipbook clips covering every band in the source sheet. */
export const ZYLEM_MAN_ANIMATIONS = [
	{ name: 'idle', frames: ['idle-0', 'idle-1', 'idle-2', 'idle-3'], speed: 0.18, loop: true },
	{ name: 'walk', frames: ['walk-0', 'walk-1', 'walk-2', 'walk-3', 'walk-4', 'walk-5'], speed: 0.1, loop: true },
	{ name: 'run', frames: ['run-0', 'run-1', 'run-2', 'run-3', 'run-4'], speed: 0.06, loop: true },
	{ name: 'duck', frames: ['duck-0', 'duck-1'], speed: 0.12, loop: false },
	{ name: 'jump', frames: ['jump-0', 'jump-1', 'jump-2', 'jump-3'], speed: 0.12, loop: false },
];

/**
 * Pixel measurements of the packed cells. `standingHeight` is the idle pose's
 * content height, which is what a caller should scale against to place the
 * character at a chosen world height; `baseline` is the distance from the
 * bottom of a cell to the shared foot line.
 */
export const ZYLEM_MAN_METRICS = {
	cellWidth: 208,
	cellHeight: 240,
	standingHeight: 205,
	baseline: 6,
};
